version: "2"

services:
  nginx:
    image: bitnami/nginx
    ports:
      - "8080:80"
    links:
      - phpfpm:phpfpm
      - mariadb:xepan-dbserver
    volumes:
      - ./server/nginx.conf:/bitnami/nginx/conf/vhosts/my.conf

  phpfpm:
    image: bitnami/php-fpm
    ports:
      - "9000:9000"
    links:
      - mariadb:xepan-dbserver
    volumes:
      - .:/app

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=winserver@#^(&
      - MYSQL_DATABASE=xepan2
    volumes:
      - "~/db-files:/var/lib/mysql"
